setup_parameters = """SYSTem:LAUNch
LTE:FDD:MODE signalAnalyzerLTEFDD
LTE:FDD:AMPlitude:PREAmp:FIRSt Off
LTE:FDD:AMPlitude:ATTenuation:VALUE 30
LTE:FDD:AMPLitude:EXTernal 44
LTE:FDD:ANTenna:SELect Auto
"""

testChannelPower = """
    LTE:FDD:MODE channelPower
    LTE:FDD:FREQuency:CENTer {cf} MHz
    LTE:FDD:CHANnel:POWer?
    LTE:FDD:CHANnel:POWer:JUDGE?
    LTE:FDD:CHANnel:POWer:SPECtral:DENSity?
    LTE:FDD:CHANnel:POWer:PTA:RATio?
"""

testOccupiedBW = """
    LTE:FDD:MODE occupiedBW
    LTE:FDD:FREQuency:CENTer {cf} MHz
    LTE:FDD:OCCupied:BW?
    LTE:FDD:OCCupied:BW:JUDGE?
    LTE:FDD:OCCupied:BW:INTegrated:POWer?
    LTE:FDD:OCCupied:BW:OCCupied:POWer?
"""

testSpectrumEmissionMask = """
    LTE:FDD:MODE spectrumEmissionMask
    LTE:FDD:FREQuency:CENTer {cf} MHz
    LTE:FDD:SEM:PEAK:LOWER1:POWER?
    LTE:FDD:SEM:PEAK:LOWER1:JUDGe?
    LTE:FDD:SEM:PEAK:UPPER1:POWER?
    LTE:FDD:SEM:PEAK:UPPER1:JUDGe?
    LTE:FDD:SEM:PEAK:LOWER2:POWER?
    LTE:FDD:SEM:PEAK:LOWER2:JUDGe?
    LTE:FDD:SEM:PEAK:UPPER2:POWER?
    LTE:FDD:SEM:PEAK:UPPER2:JUDGe?
    LTE:FDD:SEM:PEAK:LOWER3:POWER?
    LTE:FDD:SEM:PEAK:LOWER3:JUDGe?
    LTE:FDD:SEM:PEAK:UPPER3:POWER?
    LTE:FDD:SEM:PEAK:UPPER3:JUDGe?
"""

testACLR = """
    LTE:FDD:MODE adjacentChannelPower
    LTE:FDD:FREQuency:CENTer {cf} MHz
    LTE:FDD:ACP:REFERENCE:POWer?
    LTE:FDD:ACP:INTegration:LOWer01:RELATIVE:POWer?        
    LTE:FDD:ACP:INTegration:LOWER01:JUDGe?
    LTE:FDD:ACP:INTegration:LOWer01:ABSolute:POWer?
    LTE:FDD:ACP:INTegration:UPPER01:RELATIVE:POWer?    
    LTE:FDD:ACP:INTegration:UPPer01:JUDGe?
    LTE:FDD:ACP:INTegration:UPPER01:ABSolute:POWer?
    LTE:FDD:ACP:INTegration:LOWer02:RELATIVE:POWer?        
    LTE:FDD:ACP:INTegration:LOWER02:JUDGe?
    LTE:FDD:ACP:INTegration:LOWer02:ABSolute:POWer?
    LTE:FDD:ACP:INTegration:UPPER02:RELATIVE:POWer?    
    LTE:FDD:ACP:INTegration:UPPer02:JUDGe?
    LTE:FDD:ACP:INTegration:UPPER02:ABSolute:POWer?
"""

testSubframe = """
    LTE:FDD:MODE subframe
    LTE:FDD:FREQuency:CENTer {cf} MHz
    LTE:FDD:SUBFrame:POWer?
    LTE:FDD:SUBFrame:EVM:PSS?
    LTE:FDD:SUBFrame:EVM:SSS?
    LTE:FDD:SUBFrame:EVM:PB?
    LTE:FDD:SUBFrame:EVM:PCFI?
    LTE:FDD:SUBFrame:EVM:PHI?
    LTE:FDD:SUBFrame:EVM:PDC?
    LTE:FDD:SUBFrame:EVM:RS?
    LTE:FDD:SUBFrame:EVM:QAM16?
    LTE:FDD:SUBFrame:EVM:QAM64?
    LTE:FDD:SUBFrame:EVM:QAM256?
    LTE:FDD:SUBFrame:POWer:PSS?
    LTE:FDD:SUBFrame:POWer:SSS?
    LTE:FDD:SUBFrame:POWer:PB?
    LTE:FDD:SUBFrame:POWer:PCFI?
    LTE:FDD:SUBFrame:POWer:PHI?
    LTE:FDD:SUBFrame:POWer:PDC?
    LTE:FDD:SUBFrame:POWer:RS?
    LTE:FDD:SUBFrame:POWER:QAM16?
    LTE:FDD:SUBFrame:POWER:QAM64?
    LTE:FDD:SUBFrame:POWER:QAM256?
    LTE:FDD:SUBFrame:REGard:RB:QAM64?
    LTE:FDD:SUBFrame:OFDM:SYMBol:POWer?
    LTE:FDD:SUBFrame:FREQuency:ERRor:HZ?
    LTE:FDD:SUBFrame:FREQuency:ERRor:PPM?
    LTE:FDD:SUBFrame:FREQuency:ERRor:JUDGE?
    LTE:FDD:SUBFrame:TIME:ERRor?
    LTE:FDD:SUBFrame:DATA:EVM:RMS:NORMal?
    LTE:FDD:SUBFrame:DATA:EVM:RMS:ACCumulate?
    LTE:FDD:SUBFrame:DATA:EVM:PEAK:NORMAL?
    LTE:FDD:SUBFrame:DATA:EVM:PEAK:ACCumulate?
    LTE:FDD:SUBFrame:DATA:EVM:PEAK:SYMBol?
    LTE:FDD:SUBFrame:RS:EVM:RMS:NORMAL?
    LTE:FDD:SUBFrame:RS:EVM:RMS:ACCUMULATE?
    LTE:FDD:SUBFrame:RS:EVM:PEAK:NORMAL?
    LTE:FDD:SUBFrame:RS:EVM:PEAK:ACCUMULATE?
    LTE:FDD:SUBFrame:RS:EVM:PEAK:SYMBOL?
    """
